name: Amirhosein Toosi
title: Amirhosein Toosi
logo: /assets/img/0.jpeg
description: Personal webpagePersonal webpagePersonal webpagePersonal webpagePersonal webpagePersonal webpagePersonal webpage
markdown: kramdown
show_downloads: false
theme: jekyll-theme-minimal
